documentation: Ocean State Estimation Packages (converted from tex)
altMITgcm/MITgcm pull request #15
Opened 2018-01-12 19:40 UTC by gaelforget

Was originally parsed through pandoc (pandoc -s -f latex -t rst -o top_section.rst top_section.tex); webhooked to read the docs (https://mitgcm-via-hubgcm.readthedocs.io); then various issues were fixed (tables, cross-referencing, etc.).

2018-01-16 16:30 UTC, edoddridge requested changes
Thanks @gaelforget! This is a great start.

There are a few issues that we need to address before merging this PR. The most pressing is reducing the number of commits, probably to a single commit, and improving the commit message. I think [this](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) is a fairly good guide on how to squash commits together. Let me know if you'd like more guidance - I'm happy to come to the 14th floor and talk you through it.

I've gone through and highlight some places where I think we can improve on this before we merge. 

Thanks again for helping with the translation, and for testing the GitHub workflow.

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +.. FYI the corresponding tex was: (see Chapter~\ref{chap:autodiff})
These comments don't need to stay long term.

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +:raw-latex:`\cite{for-eta:15}` the total cost function is formulated
This :raw-latex: directive should be replaced a with :cite: directive. `for-eta:15` may also need to be added to the bib file.

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +.. FYI the equations below were translated by pandoc as:
More comments that don't need to stay long term.

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +.. FYI the above table was mis-handled by pandoc which had
More comments

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +  |                       |                       | section \ `1.2 <#intg             |
This (and following) section references would be simpler if they used the :numref: directive. See http://mitgcm-example.readthedocs.io/en/latest/contributing/contributing.html#internal-document-references for examples of the syntax to use.

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +
It is possible to have large sections of verbatim text by placing two colons followed by a blank line and then indenting the text.

```
::

   verbatim text
   more verbatim text
```

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +The line search optimisation algorithm [sectionoptim]
The label for this section seems to have been incorporated into the title.

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +   .. raw:: latex
This :raw-latex: directive and the others soon afterwards aren't doing anything.

2018-01-16 16:30 UTC, edoddridge commented on doc/ocean_state_est/ocean_state_est.rst
> +          |      )
This isn't a very helpful footnote. Can we clarify it somehow?

2018-01-18 07:48 UTC, gaelforget commented
Should be good to go now?

2018-01-18 07:49 UTC, gaelforget commented on doc/ocean_state_est/ocean_state_est.rst
> +
Thanks

2018-01-18 13:59 UTC, edoddridge commented
I think it's very close.

- The section references automatically get "Section" in front of the number, so there are a few spots where the text now has "section Section".
- The footnote "Not sure what this means." is still there. It's not a particularly helpful footnote for a manual to have...

2018-01-18 19:43 UTC, gaelforget commented
Done.

2018-01-18 20:25 UTC, edoddridge approved these changes

2018-01-18 20:25 UTC, edoddridge commented
LGTM

2018-01-18 20:31 UTC, christophernhill commented
Awesome - and thanks Gael! 

merging now

2018-01-18 20:31 UTC, merged